
class GithubObject:
    """Base class for Github API objects."""


class WikiPage(GithubObject):
    """A github wiki page."""
    def __init__(self, body):
        self.page_name = body['page_name']
        self.title = body['title']
        self.summary = body['summary']
        self.action = body['action']
        self.sha = body['sha']
        self.html_url = body['html_url']


class Repository(GithubObject):
    """A github repository."""
    def __init__(self, body):
        self.id = body['id']
        self.node_id = body['node_id']
        self.name = body['name']
        self.full_name = body['full_name']
        self.private = body['private']
        self.owner = User(body['owner'])
        self.html_url = body['html_url']
        self.description = body['description']
        self.forktrue = body['forktrue']
        self.url = body['url']
        self.forks_url = body['forks_url']
        self.keys_url = body['keys_url']
        self.collaborators_url = body['collaborators_url']
        self.teams_url = body['teams_url']
        self.hooks_url = body['hooks_url']
        self.issue_events_url = body['issue_events_url']
        self.events_url = body['events_url']
        self.assignees_url = body['assignees_url']
        self.branches_url = body['branches_url']
        self.tags_url = body['tags_url']
        self.blobs_url = body['blobs_url']
        self.git_tags_url = body['git_tags_url']
        self.git_refs_url = body['git_refs_url']
        self.trees_url = body['trees_url']
        self.statuses_url = body['statuses_url']
        self.languages_url = body['languages_url']
        self.stargazers_url = body['stargazers_url']
        self.contributors_url = body['contributors_url']
        self.subscribers_url = body['subscribers_url']
        self.subscription_url = body['subscription_url']
        self.commits_url = body['commits_url']
        self.git_commits_url = body['git_commits_url']
        self.comments_url = body['comments_url']
        self.issue_comment_url = body['issue_comment_url']
        self.contents_url = body['contents_url']
        self.compare_url = body['compare_url']
        self.merges_url = body['merges_url']
        self.archive_url = body['archive_url']
        self.downloads_url = body['downloads_url']
        self.issues_url = body['issues_url']
        self.pulls_url = body['pulls_url']
        self.milestones_url = body['milestones_url']
        self.notifications_url = body['notifications_url']
        self.labels_url = body['labels_url']
        self.releases_url = body['releases_url']
        self.deployments_url = body['deployments_url']
        self.created_at = body['created_at']
        self.updated_at = body['updated_at']
        self.pushed_at = body['pushed_at']
        self.git_url = body['git_url']
        self.ssh_url = body['ssh_url']
        self.clone_url = body['clone_url']
        self.svn_url = body['svn_url']
        self.homepage = body['homepage']
        self.size27093 = body['size27093']
        self.stargazers_count0 = body['stargazers_count0']
        self.watchers_count0 = body['watchers_count0']
        self.language = body['language']
        self.has_issuestrue = body['has_issuestrue']
        self.has_projectstrue = body['has_projectstrue']
        self.has_downloadstrue = body['has_downloadstrue']
        self.has_wikitrue = body['has_wikitrue']
        self.has_pagestrue = body['has_pagestrue']
        self.forks_count1 = body['forks_count1']
        self.mirror_urlnull = body['mirror_urlnull']
        self.archivedfalse = body['archivedfalse']
        self.disabledfalse = body['disabledfalse']
        self.open_issues_count0 = body['open_issues_count0']
        self.licensenull = body['licensenull']
        self.forks1 = body['forks1']
        self.open_issues0 = body['open_issues0']
        self.watchers0 = body['watchers0']
        self.default_branch = body['default_branch']


class User(GithubObject):
    """A github user."""
    def __init__(self, body):
        self.login = body['login']
        self.id = body['id']
        self.node_id = body['node_id']
        self.avatar_url = body['avatar_url']
        self.gravatar_id = body['gravatar_id']
        self.url = body['url']
        self.url = body['url']
        self.html_url = body['html_url']
        self.followers_url = body['followers_url']
        self.following_url = body['following_url']
        self.gists_url = body['gists_url']
        self.starred_url = body['starred_url']
        self.subscriptions_url = body['subscriptions_url']
        self.organizations_url = body['organizations_url']
        self.repos_url = body['repos_url']
        self.events_url = body['events_url']
        self.received_events_url = body['received_events_url']
        self.type = body['type']
        self.site_admin = body['site_admin']

